services:
  redis:
    image: redis:alpine
    container_name: wasinredis
    hostname: redis
    ports:
      - "6379:6379"

  wasin:
    image: $${ECR_WASIN_IMAGE_URL}
    ports:
      - "8080:8080"
    container_name: web_prod
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/opt/wasin/log
      - ./src/main/resources:/opt/wasin/src/main/resources
    tty: true
    restart: on-failure:2
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: server_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app/
      - ./nginx:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - wasin
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
